package io.github.santunioni.recipes.removeMapstruct

import org.openrewrite.ExecutionContext
import org.openrewrite.Tree
import org.openrewrite.internal.ListUtils
import org.openrewrite.java.JavaVisitor
import org.openrewrite.java.tree.J
import org.openrewrite.java.tree.JavaType
import org.openrewrite.java.tree.Space
import org.openrewrite.java.tree.TypeUtils
import org.openrewrite.marker.Markers
import java.util.UUID
import java.util.logging.Logger

open class MapperProcessorBare(
    private val mapstructRefsReader: MapstructRefsReader,
) : JavaVisitor<ExecutionContext>() {
    private val rewriteImplReferences = RewriteImplReferences(mapstructRefsReader)

    /**
     * Intercepts all tree-node visits to delete mapper impl files. TreeVisitor.visit is declared
     * `@Nullable T visit(@Nullable Tree, P)` in Java so Kotlin sees the return as `J?`, making it
     * safe to return null without any unchecked-cast gymnastics.
     */
    override fun visit(
        tree: Tree?,
        ctx: ExecutionContext,
    ): J? {
        if (tree is J.CompilationUnit && isMapperImplementation(tree)) {
            return null
        }
        return super.visit(tree, ctx)
    }

    /**
     * Modify the mapper declaration file with a modified mix of methods and fields from itself plus
     * the mapper implementation generated by mapstruct.
     */
    @Suppress("TooGenericExceptionCaught", "TooGenericExceptionThrown")
    override fun visitCompilationUnit(
        mapperDeclFile: J.CompilationUnit,
        ctx: ExecutionContext,
    ): J {
        val superResult = super.visitCompilationUnit(mapperDeclFile, ctx)
        val visited = superResult as? J.CompilationUnit ?: return superResult
        if (!isMapperDeclaration(visited)) return visited

        val mapperDeclClass = visited.classes[0]

        try {
            var mapperImplFile = mapstructRefsReader.getImplementer(mapperDeclClass) ?: return visited

            val mapperImplClass = mapperImplFile.classes[0]
            val mapperImplClassName = mapperImplClass.name.simpleName
            val mapperDeclClassName = mapperDeclClass.name.simpleName

            mapperImplFile = copyImports(mapperImplFile)

            // STEP B: PREPARE GENERATED METHODS (Remove @Override and rename constructors)
            val copiedClassStatements =
                (
                    mapperImplClass.body.statements.map { implStatement ->
                        when (implStatement) {
                            is J.MethodDeclaration -> {
                                transformMapperImplMethod(
                                    implStatement,
                                    mapperImplClassName,
                                    mapperDeclClassName,
                                )
                            }

                            else -> {
                                implStatement
                            }
                        }
                    } +
                        mapperDeclClass.body.statements.mapNotNull { mapperDeclStatement ->
                            when (mapperDeclStatement) {
                                is J.MethodDeclaration -> {
                                    transformMapperDeclMethod(mapperDeclStatement)
                                }

                                is J.VariableDeclarations -> {
                                    if (mapperDeclClass.kind == J.ClassDeclaration.Kind.Type.Interface) {
                                        transformMapperDeclInterfaceField(mapperDeclStatement)
                                    } else {
                                        mapperDeclStatement
                                    }
                                }

                                else -> {
                                    null
                                }
                            }
                        }
                ).sortedWith(StatementDefinitionOrder())

            var clazz =
                mapperImplClass
                    .withBody(mapperImplClass.body.withStatements(copiedClassStatements))
                    .withName(mapperImplClass.name.withSimpleName(mapperDeclClassName))
                    .withImplements(null)
                    .withLeadingAnnotations(
                        (
                            mapperDeclClass.leadingAnnotations.filter { excludeMapstructAnnotations(it) } +
                                mapperImplClass.leadingAnnotations.filter {
                                    excludeGeneratedAnnotations(it)
                                }
                        ).toMutableList(),
                    ).withExtends(null)

            // Rewrite *Impl references (new FooMapperImpl(), FooMapperImpl.class, etc.) that were
            // copied in from the generated impl body so they point back at the mapper type.
            clazz = rewriteImplReferences.visit(clazz, ctx) as? J.ClassDeclaration ?: clazz

            return mapperImplFile
                .withImports(visited.imports.filter { !it.packageName.startsWith(MAPSTRUCT_GROUP) })
                .withClasses(listOf(clazz))
                .withId(visited.id)
                .withSourcePath(visited.sourcePath)
        } catch (e: Exception) {
            log.severe("Error processing @Mapper class ${visited.classes[0].name}: ${e.message}")
            throw RuntimeException(
                "Failed to migrate Mapstruct Mapper: ${mapperDeclClass.name.simpleName}",
                e,
            )
        }
    }

    private fun copyImports(mapperImplementationFile: J.CompilationUnit): J.CompilationUnit =
        mapperImplementationFile.withImports(emptyList())

    companion object {
        private val log = Logger.getLogger(MapperProcessorBare::class.java.name)
        private const val MAPSTRUCT_GROUP = "org.mapstruct"

        private val MAPSTRUCT_ANNOTATION_SIMPLE_NAMES =
            setOf(
                "AfterMapping",
                "BeanMapping",
                "BeforeMapping",
                "Condition",
                "Context",
                "DecoratedWith",
                "EnumMapping",
                "InheritConfiguration",
                "InheritInverseConfiguration",
                "IterableMapping",
                "MapMapping",
                "Mapper",
                "MapperConfig",
                "Mapping",
                "MappingConstants",
                "Mappings",
                "MappingTarget",
                "Named",
                "ObjectFactory",
                "Qualifier",
                "SubclassMapping",
                "SubclassMappings",
                "TargetType",
                "ValueMapping",
                "ValueMappings",
            )

        private fun transformMapperDeclMethod(mapperDeclMethod: J.MethodDeclaration): J.MethodDeclaration? {
            if (mapperDeclMethod.body == null) return null

            // Replace `default` modifier with `public`
            val newModifiers =
                ListUtils.map(mapperDeclMethod.modifiers) { modifier ->
                    when (modifier.type) {
                        J.Modifier.Type.Default -> modifier.withType(J.Modifier.Type.Public)
                        else -> modifier
                    }
                } ?: mapperDeclMethod.modifiers
            var method = mapperDeclMethod.withModifiers(newModifiers)

            // Strip MapStruct annotations from the method
            method =
                method.withLeadingAnnotations(
                    ListUtils.filter(method.leadingAnnotations) { excludeMapstructAnnotations(it) }
                        ?: emptyList(),
                )

            // Strip MapStruct annotations from method parameters
            val filteredParameters =
                ListUtils.map(method.parameters) { param ->
                    when (param) {
                        is J.VariableDeclarations -> {
                            param.withLeadingAnnotations(
                                ListUtils.filter(param.leadingAnnotations) { excludeMapstructAnnotations(it) }
                                    ?: emptyList(),
                            )
                        }

                        else -> {
                            param
                        }
                    }
                } ?: method.parameters
            return method.withParameters(filteredParameters)
        }

        private fun transformMapperDeclInterfaceField(mapperDeclField: J.VariableDeclarations): J.VariableDeclarations {
            val accessModifiers = setOf(J.Modifier.Type.Public, J.Modifier.Type.Protected, J.Modifier.Type.Private)
            val modifiersSetManually = accessModifiers + setOf(J.Modifier.Type.Static, J.Modifier.Type.Final)

            val existingAccess = mapperDeclField.modifiers.firstOrNull { it.type in accessModifiers }
            val modifiers =
                buildList {
                    add(
                        existingAccess
                            ?: J.Modifier(
                                UUID.randomUUID(),
                                Space.EMPTY,
                                Markers.EMPTY,
                                null,
                                J.Modifier.Type.Public,
                                emptyList(),
                            ),
                    )
                    add(
                        J.Modifier(
                            UUID.randomUUID(),
                            Space.SINGLE_SPACE,
                            Markers.EMPTY,
                            null,
                            J.Modifier.Type.Static,
                            emptyList(),
                        ),
                    )
                    add(
                        J.Modifier(
                            UUID.randomUUID(),
                            Space.SINGLE_SPACE,
                            Markers.EMPTY,
                            null,
                            J.Modifier.Type.Final,
                            emptyList(),
                        ),
                    )
                    addAll(
                        mapperDeclField.modifiers
                            .filter { it.type !in modifiersSetManually }
                            .map { it.withPrefix(Space.SINGLE_SPACE) },
                    )
                }

            var field = mapperDeclField.withModifiers(modifiers)
            field.typeExpression?.let { field = field.withTypeExpression(it.withPrefix(Space.SINGLE_SPACE)) }
            return field
        }

        private fun transformMapperImplMethod(
            implMethod: J.MethodDeclaration,
            mapperImplClassName: String,
            mapperDeclClassName: String,
        ): J.MethodDeclaration {
            var method = implMethod

            if (method.name.simpleName == mapperImplClassName) {
                method = method.withName(method.name.withSimpleName(mapperDeclClassName))
            }

            val originalAnnotations = method.leadingAnnotations
            val prefixToPreserve =
                originalAnnotations
                    .firstOrNull { ann ->
                        ann.simpleName == "Override" ||
                            TypeUtils.isOfClassType(ann.type, "java.lang.Override")
                    }?.prefix

            // Use filter (not map with null return) to remove @Override annotations
            val filteredAnnotations =
                ListUtils.filter(originalAnnotations) { ann ->
                    ann.simpleName != "Override" && !TypeUtils.isOfClassType(ann.type, "java.lang.Override")
                } ?: emptyList()

            method = method.withLeadingAnnotations(filteredAnnotations)
            if (prefixToPreserve != null && filteredAnnotations.isEmpty()) {
                method = method.withPrefix(prefixToPreserve)
            }
            return method
        }

        private fun excludeGeneratedAnnotations(a: J.Annotation): Boolean =
            !(
                a.simpleName == "Generated" ||
                    TypeUtils.isOfClassType(a.type, "javax.annotation.processing.Generated") ||
                    TypeUtils.isOfClassType(a.type, "jakarta.annotation.Generated")
            )

        private fun excludeMapstructAnnotations(a: J.Annotation): Boolean {
            val type = a.type
            return when {
                type != null && type !is JavaType.Unknown -> !type.toString().startsWith(MAPSTRUCT_GROUP)
                else -> a.simpleName !in MAPSTRUCT_ANNOTATION_SIMPLE_NAMES
            }
        }
    }
}
