package io.github.santunioni.recipes.removeMapstruct

import org.openrewrite.ExecutionContext
import org.openrewrite.Tree
import org.openrewrite.internal.ListUtils
import org.openrewrite.java.AddImport
import org.openrewrite.java.JavaVisitor
import org.openrewrite.java.tree.Expression
import org.openrewrite.java.tree.Flag
import org.openrewrite.java.tree.J
import org.openrewrite.java.tree.JContainer
import org.openrewrite.java.tree.JRightPadded
import org.openrewrite.java.tree.JavaType
import org.openrewrite.java.tree.Space
import org.openrewrite.java.tree.TypeTree
import org.openrewrite.java.tree.TypeUtils
import org.openrewrite.marker.Markers
import java.util.UUID
import java.util.logging.Logger

open class MapperProcessorBare(
    private val acc: Accumulator,
) : JavaVisitor<ExecutionContext>() {
    /**
     * Intercepts all tree-node visits to delete mapper impl files. TreeVisitor.visit is declared
     * `@Nullable T visit(@Nullable Tree, P)` in Java so Kotlin sees the return as `J?`, making it
     * safe to return null without any unchecked-cast gymnastics.
     */
    override fun visit(
        tree: Tree?,
        ctx: ExecutionContext,
    ): J? {
        if (tree is J.CompilationUnit && isMapperImplementation(tree)) {
            return null
        }
        return super.visit(tree, ctx)
    }

    /**
     * Modify the mapper declaration file with a modified mix of methods and fields from itself plus
     * the mapper implementation generated by mapstruct.
     */
    @Suppress("TooGenericExceptionCaught", "TooGenericExceptionThrown")
    override fun visitCompilationUnit(
        mapperDeclFile: J.CompilationUnit,
        ctx: ExecutionContext,
    ): J {
        // Collect @Spy-annotated field names up front so that nested visits can rewrite
        // when(spy.x(a)).thenReturn(v) into doReturn(v).when(spy).x(a).
        val spyFieldNames = collectSpyFieldNames(mapperDeclFile)
        if (spyFieldNames.isNotEmpty()) {
            log.fine("[PurgeMapstruct] Found spy fields in ${mapperDeclFile.sourcePath}: $spyFieldNames")
        }
        cursor.putMessage(SPY_FIELD_NAMES_KEY, spyFieldNames)

        val superResult = super.visitCompilationUnit(mapperDeclFile, ctx)
        val visited = superResult as? J.CompilationUnit ?: return superResult
        if (!isMapperDeclaration(visited)) return visited

        val mapperDeclClass = visited.classes[0]

        try {
            var mapperImplFile = acc.getImplementer(mapperDeclClass) ?: return visited

            val mapperImplClass = mapperImplFile.classes[0]
            val mapperImplClassName = mapperImplClass.name.simpleName
            val mapperDeclClassName = mapperDeclClass.name.simpleName

            mapperImplFile = copyImports(mapperImplFile)

            // STEP B: PREPARE GENERATED METHODS (Remove @Override and rename constructors)
            val copiedClassStatements =
                (
                    mapperImplClass.body.statements.map { implStatement ->
                        when (implStatement) {
                            is J.MethodDeclaration -> {
                                transformMapperImplMethod(
                                    implStatement,
                                    mapperImplClassName,
                                    mapperDeclClassName,
                                )
                            }

                            else -> {
                                implStatement
                            }
                        }
                    } +
                        mapperDeclClass.body.statements.mapNotNull { mapperDeclStatement ->
                            when (mapperDeclStatement) {
                                is J.MethodDeclaration -> {
                                    transformMapperDeclMethod(mapperDeclStatement)
                                }

                                is J.VariableDeclarations -> {
                                    if (mapperDeclClass.kind == J.ClassDeclaration.Kind.Type.Interface) {
                                        transformMapperDeclInterfaceField(mapperDeclStatement)
                                    } else {
                                        mapperDeclStatement
                                    }
                                }

                                else -> {
                                    null
                                }
                            }
                        }
                ).sortedWith(StatementDefinitionOrder())

            var clazz =
                mapperImplClass
                    .withBody(mapperImplClass.body.withStatements(copiedClassStatements))
                    .withName(mapperImplClass.name.withSimpleName(mapperDeclClassName))
                    .withImplements(null)
                    .withLeadingAnnotations(
                        (
                            mapperDeclClass.leadingAnnotations.filter { excludeMapstructAnnotations(it) } +
                                mapperImplClass.leadingAnnotations.filter {
                                    excludeGeneratedAnnotations(it)
                                }
                        ).toMutableList(),
                    ).withExtends(null)

            // Visit the merged class so reference rewrites (Mappers.getMapper, *Impl refs, etc.)
            // apply to the copied impl body too.
            clazz = visit(clazz, ctx) as? J.ClassDeclaration ?: clazz

            acc.touchedSourcePaths.add(visited.sourcePath)
            return mapperImplFile
                .withClasses(listOf(clazz))
                .withId(visited.id)
                .withSourcePath(visited.sourcePath)
        } catch (e: Exception) {
            log.severe("Error processing @Mapper class ${visited.classes[0].name}: ${e.message}")
            throw RuntimeException(
                "Failed to migrate Mapstruct Mapper: ${mapperDeclClass.name.simpleName}",
                e,
            )
        }
    }

    /**
     * Replaces `Mappers.getMapper(SomeMapper.class)` with a direct constructor call `new
     * SomeMapper()`.
     */
    override fun visitMethodInvocation(
        method: J.MethodInvocation,
        ctx: ExecutionContext,
    ): J {
        val superResult = super.visitMethodInvocation(method, ctx)
        val visited = superResult as? J.MethodInvocation ?: return superResult

        val rewrittenSpyStub = rewriteWhenOnSpyIfApplicable(visited)
        if (rewrittenSpyStub != null) return rewrittenSpyStub

        if (!isMappersGetMapper(visited) || visited.arguments.size != 1) return visited

        val arg0 = visited.arguments[0]
        if (arg0 !is J.FieldAccess || arg0.name.simpleName != "class") return visited
        val classLiteral: J.FieldAccess = arg0

        val mapperType: TypeTree =
            when (val target = classLiteral.target) {
                is J.Identifier -> target.withPrefix(Space.SINGLE_SPACE)
                is J.FieldAccess -> target.withPrefix(Space.SINGLE_SPACE)
                else -> return visited
            }

        val mapperFqn = TypeUtils.asFullyQualified(mapperType.type) ?: return visited

        val constructorType =
            JavaType.Method(
                null,
                Flag.Public.bitMask,
                mapperFqn,
                "<constructor>",
                mapperFqn,
                emptyList(),
                emptyList(),
                emptyList(),
                emptyList(),
                null,
                null,
            )

        val noArguments: Expression = J.Empty(UUID.randomUUID(), Space.EMPTY, Markers.EMPTY)
        val arguments: JContainer<Expression> =
            JContainer.build(
                Space.EMPTY,
                listOf(JRightPadded.build(noArguments)),
                Markers.EMPTY,
            )

        return J.NewClass(
            UUID.randomUUID(),
            visited.prefix,
            visited.markers,
            null,
            Space.EMPTY,
            mapperType,
            arguments,
            null,
            constructorType,
        )
    }

    /**
     * Replaces references like `UserMapperImpl.class` to `UserMapper.class`, for both simple-name and
     * fully-qualified targets.
     */
    override fun visitFieldAccess(
        fieldAccess_: J.FieldAccess,
        ctx: ExecutionContext,
    ): J {
        val superResult = super.visitFieldAccess(fieldAccess_, ctx)
        val visited = superResult as? J.FieldAccess ?: return superResult

        return when (val target = visited.target) {
            // Case A: simple-name target, e.g. `UserMapperImpl.class`
            is J.Identifier -> {
                val targetFqn = target.type?.toString() ?: return visited
                val superFqn = acc.getSuperFqnFromImplFqn(targetFqn) ?: return visited
                val superType = JavaType.buildType(superFqn)
                visited
                    .withTarget(
                        J.Identifier(
                            UUID.randomUUID(),
                            target.prefix,
                            target.markers,
                            emptyList(),
                            extractSimpleName(superFqn),
                            superType,
                            target.fieldType,
                        ),
                    ).withType(superType)
            }

            // Case B: fully qualified target, e.g. `com.foo.UserMapperImpl.class`
            is J.FieldAccess -> {
                val targetFqn = extractFqnFromFieldAccess(target)
                val superFqn = acc.getSuperFqnFromImplFqn(targetFqn) ?: return visited
                val superType = JavaType.buildType(superFqn)
                visited.withTarget(
                    target.withName(target.name.withSimpleName(extractSimpleName(superFqn))).withType(superType),
                )
            }

            else -> {
                visited
            }
        }
    }

    /** Replaces import references of `UserMapperImpl` to `UserMapper`. */
    override fun visitImport(
        imp: J.Import,
        ctx: ExecutionContext,
    ): J {
        val superResult = super.visitImport(imp, ctx)
        val visited = superResult as? J.Import ?: return superResult

        val importFqn = extractFqnFromFieldAccess(visited.qualid)
        val superFqn = acc.getSuperFqnFromImplFqn(importFqn) ?: return visited

        if (importFqn == superFqn) return visited

        val currentSimpleName = getFinalIdentifierName(visited.qualid)
        val expectedSimpleName = extractSimpleName(superFqn)
        if (currentSimpleName == expectedSimpleName && !currentSimpleName.endsWith("Impl")) {
            return visited
        }

        return replaceImportQualid(visited, superFqn)
    }

    /** Replaces instantiations of `UserMapperImpl()` to `UserMapper()`. */
    override fun visitNewClass(
        newClass: J.NewClass,
        ctx: ExecutionContext,
    ): J {
        val superResult = super.visitNewClass(newClass, ctx)
        val visited = superResult as? J.NewClass ?: return superResult

        val clazz = visited.clazz ?: return visited
        val replacedClazz = replaceTypeTreeIfNeeded(clazz)
        if (replacedClazz === clazz) return visited
        return visited.withClazz(replacedClazz)
    }

    /** Replaces variable declarations like `UserMapperImpl userMapper` to `UserMapper userMapper`. */
    override fun visitVariableDeclarations(
        multiVariable: J.VariableDeclarations,
        p: ExecutionContext,
    ): J {
        val superResult = super.visitVariableDeclarations(multiVariable, p)
        val visited = superResult as? J.VariableDeclarations ?: return superResult

        val typeExpression = visited.typeExpression ?: return visited
        val replacedTypeExpression = replaceTypeTreeIfNeeded(typeExpression)
        if (replacedTypeExpression === typeExpression) return visited
        return visited.withTypeExpression(replacedTypeExpression)
    }

    /**
     * Replaces instanceof checks like `userMapper instanceof UserMapperImpl` to `userMapper
     * instanceof UserMapper`.
     */
    @Suppress("UNCHECKED_CAST")
    override fun visitInstanceOf(
        instanceOf_: J.InstanceOf,
        ctx: ExecutionContext,
    ): J {
        val superResult = super.visitInstanceOf(instanceOf_, ctx)
        val visited = superResult as? J.InstanceOf ?: return superResult

        val clazzExpr = visited.clazz as? J.ControlParentheses<*> ?: return visited
        val treeObj = clazzExpr.tree as? TypeTree ?: return visited

        val replacedClazz = replaceTypeTreeIfNeeded(treeObj)
        if (replacedClazz === treeObj) return visited

        // Cast required because J.ControlParentheses<*> (star projection) blocks withTree().
        return visited.withClazz((clazzExpr as J.ControlParentheses<TypeTree>).withTree(replacedClazz))
    }

    private fun copyImports(mapperImplementationFile: J.CompilationUnit): J.CompilationUnit =
        mapperImplementationFile.withImports(emptyList())

    private fun extractFqnFromFieldAccess(fieldAccess: J.FieldAccess): String {
        val parts =
            buildList {
                add(fieldAccess.name.simpleName)
                var current: Expression = fieldAccess.target
                while (current is J.FieldAccess) {
                    add(current.name.simpleName)
                    current = current.target
                }
                if (current is J.Identifier) add(current.simpleName)
            }
        return parts.reversed().joinToString(".")
    }

    private fun replaceTypeTreeIfNeeded(typeTree: TypeTree): TypeTree {
        val type = typeTree.type as? JavaType.FullyQualified ?: return typeTree
        val typeFqn = type.fullyQualifiedName
        val superFqn = acc.getSuperFqnFromImplFqn(typeFqn) ?: return typeTree
        val superSimpleName = extractSimpleName(superFqn)
        val superType = JavaType.buildType(superFqn)
        return J.Identifier(
            UUID.randomUUID(),
            typeTree.prefix,
            typeTree.markers,
            emptyList(),
            superSimpleName,
            superType,
            null,
        )
    }

    private fun replaceImportQualid(
        import_: J.Import,
        superFqn: String,
    ): J.Import {
        val superSimpleName = extractSimpleName(superFqn)
        val qualid = import_.qualid
        val newQualid = qualid.withName(qualid.name.withSimpleName(superSimpleName))
        return import_.withQualid(newQualid)
    }

    private fun extractSimpleName(fqn: String): String = fqn.substringAfterLast('.')

    private fun getFinalIdentifierName(fieldAccess: J.FieldAccess): String =
        generateSequence(fieldAccess) { it.target as? J.FieldAccess }.last().name.simpleName

    /**
     * If `invocation` matches `when(spy.method(args)).thenReturn(value)` where `spy` is a locally
     * declared `@Spy` field, rebuilds the tree as `doReturn(value).when(spy).method(args)` and adds
     * the necessary Mockito static import. Returns `null` when the pattern doesn't match.
     */
    private fun rewriteWhenOnSpyIfApplicable(invocation: J.MethodInvocation): J.MethodInvocation? {
        val stubName = invocation.simpleName
        if (stubName != "thenReturn" && stubName != "thenThrow") return null
        if (invocation.arguments.size != 1) return null

        val whenInvocation = invocation.select as? J.MethodInvocation ?: return null
        if (whenInvocation.simpleName != "when" || whenInvocation.arguments.size != 1) return null

        val spyMethodCall = whenInvocation.arguments[0] as? J.MethodInvocation ?: return null
        val spyIdent = spyMethodCall.select as? J.Identifier ?: return null

        val spyNames: Set<String>? = cursor.getNearestMessage(SPY_FIELD_NAMES_KEY)
        log.fine(
            "[PurgeMapstruct] Checking when-spy: candidate=${spyIdent.simpleName} known-spies=$spyNames",
        )
        if (spyNames == null || spyIdent.simpleName !in spyNames) return null

        val doStubName = if (stubName == "thenReturn") "doReturn" else "doThrow"
        val stubValue = invocation.arguments[0]

        val mockitoType = JavaType.buildType("org.mockito.Mockito") as JavaType.FullyQualified
        val stubberType = JavaType.buildType("org.mockito.stubbing.Stubber") as JavaType.FullyQualified

        val doStubMethodType =
            JavaType.Method(
                null,
                Flag.Public.bitMask or Flag.Static.bitMask,
                mockitoType,
                doStubName,
                stubberType,
                listOf("value"),
                listOf(stubValue.type ?: JavaType.buildType("java.lang.Object")),
                emptyList(),
                emptyList(),
                null,
                null,
            )

        val doStubIdent =
            J.Identifier(
                UUID.randomUUID(),
                Space.EMPTY,
                Markers.EMPTY,
                emptyList(),
                doStubName,
                doStubMethodType,
                null,
            )
        val doStubArgs: JContainer<Expression> =
            JContainer.build(
                Space.EMPTY,
                listOf(JRightPadded.build(stubValue.withPrefix(Space.EMPTY))),
                Markers.EMPTY,
            )
        val doStubCall =
            J.MethodInvocation(
                UUID.randomUUID(),
                invocation.prefix,
                invocation.markers,
                null,
                null,
                doStubIdent,
                doStubArgs,
                doStubMethodType,
            )

        val newWhenCall =
            J.MethodInvocation(
                UUID.randomUUID(),
                Space.EMPTY,
                whenInvocation.markers,
                JRightPadded.build(doStubCall as Expression),
                null,
                whenInvocation.name.withPrefix(Space.EMPTY),
                JContainer.build(
                    Space.EMPTY,
                    listOf(
                        JRightPadded.build(spyIdent.withPrefix(Space.EMPTY)),
                    ),
                    Markers.EMPTY,
                ),
                whenInvocation.methodType,
            )

        val spyArgs = spyMethodCall.arguments
        val paddedFinalArgs: List<JRightPadded<Expression>> =
            spyArgs.mapIndexed { i, arg ->
                val prefix = if (i == 0) Space.EMPTY else Space.SINGLE_SPACE
                JRightPadded.build(arg.withPrefix(prefix))
            }

        val finalCall =
            J.MethodInvocation(
                UUID.randomUUID(),
                Space.EMPTY,
                spyMethodCall.markers,
                JRightPadded.build(newWhenCall as Expression),
                null,
                spyMethodCall.name.withPrefix(Space.EMPTY),
                JContainer.build(Space.EMPTY, paddedFinalArgs, Markers.EMPTY),
                spyMethodCall.methodType,
            )

        doAfterVisit(AddImport("org.mockito.Mockito", doStubName, false))
        return finalCall
    }

    companion object {
        private val log = Logger.getLogger(MapperProcessorBare::class.java.name)
        private const val MAPSTRUCT_GROUP = "org.mapstruct"

        /** Cursor message key: `Set<String>` of local field names annotated with Mockito's `@Spy`. */
        private const val SPY_FIELD_NAMES_KEY = "purgeMapstruct.spyFieldNames"

        private val MAPSTRUCT_ANNOTATION_SIMPLE_NAMES =
            setOf(
                "AfterMapping",
                "BeanMapping",
                "BeforeMapping",
                "Condition",
                "Context",
                "DecoratedWith",
                "EnumMapping",
                "InheritConfiguration",
                "InheritInverseConfiguration",
                "IterableMapping",
                "MapMapping",
                "Mapper",
                "MapperConfig",
                "Mapping",
                "MappingConstants",
                "Mappings",
                "MappingTarget",
                "Named",
                "ObjectFactory",
                "Qualifier",
                "SubclassMapping",
                "SubclassMappings",
                "TargetType",
                "ValueMapping",
                "ValueMappings",
            )

        private fun transformMapperDeclMethod(mapperDeclMethod: J.MethodDeclaration): J.MethodDeclaration? {
            if (mapperDeclMethod.body == null) return null

            // Replace `default` modifier with `public`
            val newModifiers =
                ListUtils.map(mapperDeclMethod.modifiers) { modifier ->
                    when (modifier.type) {
                        J.Modifier.Type.Default -> modifier.withType(J.Modifier.Type.Public)
                        else -> modifier
                    }
                } ?: mapperDeclMethod.modifiers
            var method = mapperDeclMethod.withModifiers(newModifiers)

            // Strip MapStruct annotations from the method
            method =
                method.withLeadingAnnotations(
                    ListUtils.filter(method.leadingAnnotations) { excludeMapstructAnnotations(it) }
                        ?: emptyList(),
                )

            // Strip MapStruct annotations from method parameters
            val filteredParameters =
                ListUtils.map(method.parameters) { param ->
                    when (param) {
                        is J.VariableDeclarations -> {
                            param.withLeadingAnnotations(
                                ListUtils.filter(param.leadingAnnotations) { excludeMapstructAnnotations(it) }
                                    ?: emptyList(),
                            )
                        }

                        else -> {
                            param
                        }
                    }
                } ?: method.parameters
            return method.withParameters(filteredParameters)
        }

        private fun transformMapperDeclInterfaceField(mapperDeclField: J.VariableDeclarations): J.VariableDeclarations {
            val accessModifiers = setOf(J.Modifier.Type.Public, J.Modifier.Type.Protected, J.Modifier.Type.Private)
            val modifiersSetManually = accessModifiers + setOf(J.Modifier.Type.Static, J.Modifier.Type.Final)

            val existingAccess = mapperDeclField.modifiers.firstOrNull { it.type in accessModifiers }
            val modifiers =
                buildList {
                    add(
                        existingAccess
                            ?: J.Modifier(
                                UUID.randomUUID(),
                                Space.EMPTY,
                                Markers.EMPTY,
                                null,
                                J.Modifier.Type.Public,
                                emptyList(),
                            ),
                    )
                    add(
                        J.Modifier(
                            UUID.randomUUID(),
                            Space.SINGLE_SPACE,
                            Markers.EMPTY,
                            null,
                            J.Modifier.Type.Static,
                            emptyList(),
                        ),
                    )
                    add(
                        J.Modifier(
                            UUID.randomUUID(),
                            Space.SINGLE_SPACE,
                            Markers.EMPTY,
                            null,
                            J.Modifier.Type.Final,
                            emptyList(),
                        ),
                    )
                    addAll(
                        mapperDeclField.modifiers
                            .filter { it.type !in modifiersSetManually }
                            .map { it.withPrefix(Space.SINGLE_SPACE) },
                    )
                }

            var field = mapperDeclField.withModifiers(modifiers)
            field.typeExpression?.let { field = field.withTypeExpression(it.withPrefix(Space.SINGLE_SPACE)) }
            return field
        }

        private fun transformMapperImplMethod(
            implMethod: J.MethodDeclaration,
            mapperImplClassName: String,
            mapperDeclClassName: String,
        ): J.MethodDeclaration {
            var method = implMethod

            if (method.name.simpleName == mapperImplClassName) {
                method = method.withName(method.name.withSimpleName(mapperDeclClassName))
            }

            val originalAnnotations = method.leadingAnnotations
            val prefixToPreserve =
                originalAnnotations
                    .firstOrNull { ann ->
                        ann.simpleName == "Override" ||
                            TypeUtils.isOfClassType(ann.type, "java.lang.Override")
                    }?.prefix

            // Use filter (not map with null return) to remove @Override annotations
            val filteredAnnotations =
                ListUtils.filter(originalAnnotations) { ann ->
                    ann.simpleName != "Override" && !TypeUtils.isOfClassType(ann.type, "java.lang.Override")
                } ?: emptyList()

            method = method.withLeadingAnnotations(filteredAnnotations)
            if (prefixToPreserve != null && filteredAnnotations.isEmpty()) {
                method = method.withPrefix(prefixToPreserve)
            }
            return method
        }

        private fun excludeGeneratedAnnotations(a: J.Annotation): Boolean =
            !(
                a.simpleName == "Generated" ||
                    TypeUtils.isOfClassType(a.type, "javax.annotation.processing.Generated") ||
                    TypeUtils.isOfClassType(a.type, "jakarta.annotation.Generated")
            )

        private fun excludeMapstructAnnotations(a: J.Annotation): Boolean {
            val type = a.type
            return when {
                type != null && type !is JavaType.Unknown -> !type.toString().startsWith(MAPSTRUCT_GROUP)
                else -> a.simpleName !in MAPSTRUCT_ANNOTATION_SIMPLE_NAMES
            }
        }

        private fun collectSpyFieldNames(cu: J.CompilationUnit): Set<String> =
            cu.classes
                .asSequence()
                .flatMap { it.body.statements }
                .filterIsInstance<J.VariableDeclarations>()
                .filter { stmt ->
                    stmt.leadingAnnotations.any { a ->
                        a.simpleName == "Spy" || TypeUtils.isOfClassType(a.type, "org.mockito.Spy")
                    }
                }.flatMap { it.variables }
                .map { it.simpleName }
                .toSet()

        private fun isMappersGetMapper(invocation: J.MethodInvocation): Boolean {
            if (invocation.simpleName != "getMapper") return false
            val declaringType = invocation.methodType?.declaringType
            return when {
                declaringType != null -> {
                    declaringType.fullyQualifiedName == "org.mapstruct.factory.Mappers"
                }

                else -> {
                    when (val select = invocation.select) {
                        is J.Identifier -> select.simpleName == "Mappers"
                        is J.FieldAccess -> select.name.simpleName == "Mappers"
                        else -> false
                    }
                }
            }
        }
    }
}
