package io.github.santunioni.recipes.removeMapstruct

import org.openrewrite.ExecutionContext
import org.openrewrite.Tree
import org.openrewrite.internal.ListUtils
import org.openrewrite.java.JavaVisitor
import org.openrewrite.java.tree.Expression
import org.openrewrite.java.tree.J
import org.openrewrite.java.tree.JavaType
import org.openrewrite.java.tree.Space
import org.openrewrite.java.tree.TypeTree
import org.openrewrite.java.tree.TypeUtils
import org.openrewrite.marker.Markers
import java.util.UUID
import java.util.logging.Logger

open class MapperProcessorBare(
    private val acc: Accumulator,
) : JavaVisitor<ExecutionContext>() {
    /**
     * Intercepts all tree-node visits to delete mapper impl files. TreeVisitor.visit is declared
     * `@Nullable T visit(@Nullable Tree, P)` in Java so Kotlin sees the return as `J?`, making it
     * safe to return null without any unchecked-cast gymnastics.
     */
    override fun visit(
        tree: Tree?,
        ctx: ExecutionContext,
    ): J? {
        if (tree is J.CompilationUnit && isMapperImplementation(tree)) {
            return null
        }
        return super.visit(tree, ctx)
    }

    /**
     * Modify the mapper declaration file with a modified mix of methods and fields from itself plus
     * the mapper implementation generated by mapstruct.
     */
    @Suppress("TooGenericExceptionCaught", "TooGenericExceptionThrown")
    override fun visitCompilationUnit(
        mapperDeclFile: J.CompilationUnit,
        ctx: ExecutionContext,
    ): J {
        val superResult = super.visitCompilationUnit(mapperDeclFile, ctx)
        val visited = superResult as? J.CompilationUnit ?: return superResult
        if (!isMapperDeclaration(visited)) return visited

        val mapperDeclClass = visited.classes[0]

        try {
            var mapperImplFile = acc.getImplementer(mapperDeclClass) ?: return visited

            val mapperImplClass = mapperImplFile.classes[0]
            val mapperImplClassName = mapperImplClass.name.simpleName
            val mapperDeclClassName = mapperDeclClass.name.simpleName

            mapperImplFile = copyImports(mapperImplFile)

            // STEP B: PREPARE GENERATED METHODS (Remove @Override and rename constructors)
            val copiedClassStatements =
                (
                    mapperImplClass.body.statements.map { implStatement ->
                        when (implStatement) {
                            is J.MethodDeclaration -> {
                                transformMapperImplMethod(
                                    implStatement,
                                    mapperImplClassName,
                                    mapperDeclClassName,
                                )
                            }

                            else -> {
                                implStatement
                            }
                        }
                    } +
                        mapperDeclClass.body.statements.mapNotNull { mapperDeclStatement ->
                            when (mapperDeclStatement) {
                                is J.MethodDeclaration -> {
                                    transformMapperDeclMethod(mapperDeclStatement)
                                }

                                is J.VariableDeclarations -> {
                                    if (mapperDeclClass.kind == J.ClassDeclaration.Kind.Type.Interface) {
                                        transformMapperDeclInterfaceField(mapperDeclStatement)
                                    } else {
                                        mapperDeclStatement
                                    }
                                }

                                else -> {
                                    null
                                }
                            }
                        }
                ).sortedWith(StatementDefinitionOrder())

            var clazz =
                mapperImplClass
                    .withBody(mapperImplClass.body.withStatements(copiedClassStatements))
                    .withName(mapperImplClass.name.withSimpleName(mapperDeclClassName))
                    .withImplements(null)
                    .withLeadingAnnotations(
                        (
                            mapperDeclClass.leadingAnnotations.filter { excludeMapstructAnnotations(it) } +
                                mapperImplClass.leadingAnnotations.filter {
                                    excludeGeneratedAnnotations(it)
                                }
                        ).toMutableList(),
                    ).withExtends(null)

            // Visit the merged class so reference rewrites (Mappers.getMapper, *Impl refs, etc.)
            // apply to the copied impl body too.
            clazz = visit(clazz, ctx) as? J.ClassDeclaration ?: clazz

            return mapperImplFile
                .withImports(visited.imports.filter { !it.packageName.startsWith(MAPSTRUCT_GROUP) })
                .withClasses(listOf(clazz))
                .withId(visited.id)
                .withSourcePath(visited.sourcePath)
        } catch (e: Exception) {
            log.severe("Error processing @Mapper class ${visited.classes[0].name}: ${e.message}")
            throw RuntimeException(
                "Failed to migrate Mapstruct Mapper: ${mapperDeclClass.name.simpleName}",
                e,
            )
        }
    }

    /**
     * Replaces references like `UserMapperImpl.class` to `UserMapper.class`, for both simple-name and
     * fully-qualified targets.
     */
    override fun visitFieldAccess(
        fieldAccess_: J.FieldAccess,
        ctx: ExecutionContext,
    ): J {
        val superResult = super.visitFieldAccess(fieldAccess_, ctx)
        val visited = superResult as? J.FieldAccess ?: return superResult

        return when (val target = visited.target) {
            // Case A: simple-name target, e.g. `UserMapperImpl.class`
            is J.Identifier -> {
                val targetFqn = target.type?.toString() ?: return visited
                val superFqn = acc.getSuperFqnFromImplFqn(targetFqn) ?: return visited
                val superType = JavaType.buildType(superFqn)
                visited
                    .withTarget(
                        J.Identifier(
                            UUID.randomUUID(),
                            target.prefix,
                            target.markers,
                            emptyList(),
                            extractSimpleName(superFqn),
                            superType,
                            target.fieldType,
                        ),
                    ).withType(superType)
            }

            // Case B: fully qualified target, e.g. `com.foo.UserMapperImpl.class`
            is J.FieldAccess -> {
                val targetFqn = extractFqnFromFieldAccess(target)
                val superFqn = acc.getSuperFqnFromImplFqn(targetFqn) ?: return visited
                val superType = JavaType.buildType(superFqn)
                visited.withTarget(
                    target.withName(target.name.withSimpleName(extractSimpleName(superFqn))).withType(superType),
                )
            }

            else -> {
                visited
            }
        }
    }

    /** Replaces import references of `UserMapperImpl` to `UserMapper`. */
    override fun visitImport(
        imp: J.Import,
        ctx: ExecutionContext,
    ): J {
        val superResult = super.visitImport(imp, ctx)
        val visited = superResult as? J.Import ?: return superResult

        val importFqn = extractFqnFromFieldAccess(visited.qualid)
        val superFqn = acc.getSuperFqnFromImplFqn(importFqn) ?: return visited

        if (importFqn == superFqn) return visited

        val currentSimpleName = getFinalIdentifierName(visited.qualid)
        val expectedSimpleName = extractSimpleName(superFqn)
        if (currentSimpleName == expectedSimpleName && !currentSimpleName.endsWith("Impl")) {
            return visited
        }

        return replaceImportQualid(visited, superFqn)
    }

    /** Replaces instantiations of `UserMapperImpl()` to `UserMapper()`. */
    override fun visitNewClass(
        newClass: J.NewClass,
        ctx: ExecutionContext,
    ): J {
        val superResult = super.visitNewClass(newClass, ctx)
        val visited = superResult as? J.NewClass ?: return superResult

        val clazz = visited.clazz ?: return visited
        val replacedClazz = replaceTypeTreeIfNeeded(clazz)
        if (replacedClazz === clazz) return visited
        return visited.withClazz(replacedClazz)
    }

    /** Replaces variable declarations like `UserMapperImpl userMapper` to `UserMapper userMapper`. */
    override fun visitVariableDeclarations(
        multiVariable: J.VariableDeclarations,
        p: ExecutionContext,
    ): J {
        val superResult = super.visitVariableDeclarations(multiVariable, p)
        val visited = superResult as? J.VariableDeclarations ?: return superResult

        val typeExpression = visited.typeExpression ?: return visited
        val replacedTypeExpression = replaceTypeTreeIfNeeded(typeExpression)
        if (replacedTypeExpression === typeExpression) return visited
        return visited.withTypeExpression(replacedTypeExpression)
    }

    /**
     * Replaces instanceof checks like `userMapper instanceof UserMapperImpl` to `userMapper
     * instanceof UserMapper`.
     */
    @Suppress("UNCHECKED_CAST")
    override fun visitInstanceOf(
        instanceOf_: J.InstanceOf,
        ctx: ExecutionContext,
    ): J {
        val superResult = super.visitInstanceOf(instanceOf_, ctx)
        val visited = superResult as? J.InstanceOf ?: return superResult

        val clazzExpr = visited.clazz as? J.ControlParentheses<*> ?: return visited
        val treeObj = clazzExpr.tree as? TypeTree ?: return visited

        val replacedClazz = replaceTypeTreeIfNeeded(treeObj)
        if (replacedClazz === treeObj) return visited

        // Cast required because J.ControlParentheses<*> (star projection) blocks withTree().
        return visited.withClazz((clazzExpr as J.ControlParentheses<TypeTree>).withTree(replacedClazz))
    }

    private fun copyImports(mapperImplementationFile: J.CompilationUnit): J.CompilationUnit =
        mapperImplementationFile.withImports(emptyList())

    private fun extractFqnFromFieldAccess(fieldAccess: J.FieldAccess): String {
        val parts =
            buildList {
                add(fieldAccess.name.simpleName)
                var current: Expression = fieldAccess.target
                while (current is J.FieldAccess) {
                    add(current.name.simpleName)
                    current = current.target
                }
                if (current is J.Identifier) add(current.simpleName)
            }
        return parts.reversed().joinToString(".")
    }

    private fun replaceTypeTreeIfNeeded(typeTree: TypeTree): TypeTree {
        val type = typeTree.type as? JavaType.FullyQualified ?: return typeTree
        val typeFqn = type.fullyQualifiedName
        val superFqn = acc.getSuperFqnFromImplFqn(typeFqn) ?: return typeTree
        val superSimpleName = extractSimpleName(superFqn)
        val superType = JavaType.buildType(superFqn)
        return J.Identifier(
            UUID.randomUUID(),
            typeTree.prefix,
            typeTree.markers,
            emptyList(),
            superSimpleName,
            superType,
            null,
        )
    }

    private fun replaceImportQualid(
        import_: J.Import,
        superFqn: String,
    ): J.Import {
        val superSimpleName = extractSimpleName(superFqn)
        val qualid = import_.qualid
        val newQualid = qualid.withName(qualid.name.withSimpleName(superSimpleName))
        return import_.withQualid(newQualid)
    }

    private fun extractSimpleName(fqn: String): String = fqn.substringAfterLast('.')

    private fun getFinalIdentifierName(fieldAccess: J.FieldAccess): String =
        generateSequence(fieldAccess) { it.target as? J.FieldAccess }.last().name.simpleName

    companion object {
        private val log = Logger.getLogger(MapperProcessorBare::class.java.name)
        private const val MAPSTRUCT_GROUP = "org.mapstruct"

        private val MAPSTRUCT_ANNOTATION_SIMPLE_NAMES =
            setOf(
                "AfterMapping",
                "BeanMapping",
                "BeforeMapping",
                "Condition",
                "Context",
                "DecoratedWith",
                "EnumMapping",
                "InheritConfiguration",
                "InheritInverseConfiguration",
                "IterableMapping",
                "MapMapping",
                "Mapper",
                "MapperConfig",
                "Mapping",
                "MappingConstants",
                "Mappings",
                "MappingTarget",
                "Named",
                "ObjectFactory",
                "Qualifier",
                "SubclassMapping",
                "SubclassMappings",
                "TargetType",
                "ValueMapping",
                "ValueMappings",
            )

        private fun transformMapperDeclMethod(mapperDeclMethod: J.MethodDeclaration): J.MethodDeclaration? {
            if (mapperDeclMethod.body == null) return null

            // Replace `default` modifier with `public`
            val newModifiers =
                ListUtils.map(mapperDeclMethod.modifiers) { modifier ->
                    when (modifier.type) {
                        J.Modifier.Type.Default -> modifier.withType(J.Modifier.Type.Public)
                        else -> modifier
                    }
                } ?: mapperDeclMethod.modifiers
            var method = mapperDeclMethod.withModifiers(newModifiers)

            // Strip MapStruct annotations from the method
            method =
                method.withLeadingAnnotations(
                    ListUtils.filter(method.leadingAnnotations) { excludeMapstructAnnotations(it) }
                        ?: emptyList(),
                )

            // Strip MapStruct annotations from method parameters
            val filteredParameters =
                ListUtils.map(method.parameters) { param ->
                    when (param) {
                        is J.VariableDeclarations -> {
                            param.withLeadingAnnotations(
                                ListUtils.filter(param.leadingAnnotations) { excludeMapstructAnnotations(it) }
                                    ?: emptyList(),
                            )
                        }

                        else -> {
                            param
                        }
                    }
                } ?: method.parameters
            return method.withParameters(filteredParameters)
        }

        private fun transformMapperDeclInterfaceField(mapperDeclField: J.VariableDeclarations): J.VariableDeclarations {
            val accessModifiers = setOf(J.Modifier.Type.Public, J.Modifier.Type.Protected, J.Modifier.Type.Private)
            val modifiersSetManually = accessModifiers + setOf(J.Modifier.Type.Static, J.Modifier.Type.Final)

            val existingAccess = mapperDeclField.modifiers.firstOrNull { it.type in accessModifiers }
            val modifiers =
                buildList {
                    add(
                        existingAccess
                            ?: J.Modifier(
                                UUID.randomUUID(),
                                Space.EMPTY,
                                Markers.EMPTY,
                                null,
                                J.Modifier.Type.Public,
                                emptyList(),
                            ),
                    )
                    add(
                        J.Modifier(
                            UUID.randomUUID(),
                            Space.SINGLE_SPACE,
                            Markers.EMPTY,
                            null,
                            J.Modifier.Type.Static,
                            emptyList(),
                        ),
                    )
                    add(
                        J.Modifier(
                            UUID.randomUUID(),
                            Space.SINGLE_SPACE,
                            Markers.EMPTY,
                            null,
                            J.Modifier.Type.Final,
                            emptyList(),
                        ),
                    )
                    addAll(
                        mapperDeclField.modifiers
                            .filter { it.type !in modifiersSetManually }
                            .map { it.withPrefix(Space.SINGLE_SPACE) },
                    )
                }

            var field = mapperDeclField.withModifiers(modifiers)
            field.typeExpression?.let { field = field.withTypeExpression(it.withPrefix(Space.SINGLE_SPACE)) }
            return field
        }

        private fun transformMapperImplMethod(
            implMethod: J.MethodDeclaration,
            mapperImplClassName: String,
            mapperDeclClassName: String,
        ): J.MethodDeclaration {
            var method = implMethod

            if (method.name.simpleName == mapperImplClassName) {
                method = method.withName(method.name.withSimpleName(mapperDeclClassName))
            }

            val originalAnnotations = method.leadingAnnotations
            val prefixToPreserve =
                originalAnnotations
                    .firstOrNull { ann ->
                        ann.simpleName == "Override" ||
                            TypeUtils.isOfClassType(ann.type, "java.lang.Override")
                    }?.prefix

            // Use filter (not map with null return) to remove @Override annotations
            val filteredAnnotations =
                ListUtils.filter(originalAnnotations) { ann ->
                    ann.simpleName != "Override" && !TypeUtils.isOfClassType(ann.type, "java.lang.Override")
                } ?: emptyList()

            method = method.withLeadingAnnotations(filteredAnnotations)
            if (prefixToPreserve != null && filteredAnnotations.isEmpty()) {
                method = method.withPrefix(prefixToPreserve)
            }
            return method
        }

        private fun excludeGeneratedAnnotations(a: J.Annotation): Boolean =
            !(
                a.simpleName == "Generated" ||
                    TypeUtils.isOfClassType(a.type, "javax.annotation.processing.Generated") ||
                    TypeUtils.isOfClassType(a.type, "jakarta.annotation.Generated")
            )

        private fun excludeMapstructAnnotations(a: J.Annotation): Boolean {
            val type = a.type
            return when {
                type != null && type !is JavaType.Unknown -> !type.toString().startsWith(MAPSTRUCT_GROUP)
                else -> a.simpleName !in MAPSTRUCT_ANNOTATION_SIMPLE_NAMES
            }
        }
    }
}
