package io.github.santunioni.recipes.removeMapstruct

import io.github.santunioni.recipes.removeMapstruct.Functions.isMapperDeclaration
import io.github.santunioni.recipes.removeMapstruct.Functions.isMapperImplementation
import lombok.extern.java.Log
import org.jspecify.annotations.NullMarked
import org.openrewrite.ExecutionContext
import org.openrewrite.internal.ListUtils
import org.openrewrite.java.AddImport
import org.openrewrite.java.JavaVisitor
import org.openrewrite.java.tree.*
import org.openrewrite.marker.Markers
import java.lang.String
import java.util.*
import java.util.Set
import java.util.function.Predicate
import java.util.function.UnaryOperator
import java.util.stream.Stream
import kotlin.Any
import kotlin.Boolean
import kotlin.Exception
import kotlin.RuntimeException
import kotlin.collections.ArrayList
import kotlin.collections.HashSet
import kotlin.collections.MutableList
import kotlin.collections.MutableSet
import kotlin.collections.dropLastWhile
import kotlin.collections.indices
import kotlin.collections.mutableListOf
import kotlin.collections.mutableSetOf
import kotlin.collections.sort
import kotlin.collections.toTypedArray
import kotlin.text.endsWith
import kotlin.text.isEmpty
import kotlin.text.lastIndexOf
import kotlin.text.split
import kotlin.text.startsWith
import kotlin.text.substring
import kotlin.text.toRegex

@Log
@NullMarked
class MapperProcessor(
    private val acc: Accumulator,
) : JavaVisitor<ExecutionContext>() {
    /**
     * Modify the mapper declaration file with a modified mix of methods and fields from itself plus
     * the mapper implementation generated by mapstruct
     */
    override fun visitCompilationUnit(
        mapperDeclFile_: J.CompilationUnit,
        ctx: ExecutionContext,
    ): J? {
        // The mapstruct-generated implementation has been merged into the original @Mapper
        // declaration file (which keeps its own source path). Delete the now-redundant
        // generated source by returning null.
        if (isMapperImplementation(mapperDeclFile_)) {
            return null
        }

        // Collect @Spy-annotated field names up front so that nested visits can rewrite
        // when(spy.x(a)).thenReturn(v) into doReturn(v).when(spy).x(a).
        val spyFieldNames: MutableSet<String> = collectSpyFieldNames(mapperDeclFile_)
        if (!spyFieldNames.isEmpty()) {
            MapperProcessor.log.fine("[PurgeMapstruct] Found spy fields in " + mapperDeclFile_.getSourcePath() + ": " + spyFieldNames)
        }
        getCursor().putMessage(SPY_FIELD_NAMES_KEY, spyFieldNames)

        val visited = super.visitCompilationUnit(mapperDeclFile_, ctx)
        if (visited !is J.CompilationUnit) {
            return visited
        }

        if (!isMapperDeclaration(visited)) {
            return visited
        }

        val mapperDeclClass = visited.getClasses().get(0)

        try {
            var mapperImplFile = acc.getImplementer(mapperDeclClass)
            if (mapperImplFile == null) {
                return super.visitCompilationUnit(visited, ctx)
            }

            val mapperImplClass = mapperImplFile.getClasses().get(0)
            val mapperImplClassName = mapperImplClass.getName().getSimpleName()
            val mapperDeclClassName = mapperDeclClass.getName().getSimpleName()

            mapperImplFile = copyImports(mapperImplFile, visited)

            // ==========================================================
            // STEP B: PREPARE GENERATED METHODS (Remove @Override and rename constructors)
            // ==========================================================
            val copiedClassStatements: MutableList<Statement> = ArrayList<Statement>()

            // Transform methods on Impl class
            for (implStatement in mapperImplClass.getBody().getStatements()) {
                if (implStatement is J.MethodDeclaration) {
                    copiedClassStatements.add(
                        transformMapperImplMethod(implStatement, mapperImplClassName, mapperDeclClassName),
                    )
                } else {
                    copiedClassStatements.add(implStatement)
                }
            }

            for (mapperDeclStatement in mapperDeclClass.getBody().getStatements()) {
                if (mapperDeclStatement is J.MethodDeclaration) {
                    val mapperDeclMethodNullable: J.MethodDeclaration? = transformMapperDeclMethod(mapperDeclStatement)
                    if (mapperDeclMethodNullable != null) {
                        copiedClassStatements.add(mapperDeclMethodNullable)
                    }
                } else if (mapperDeclStatement is J.VariableDeclarations) {
                    if (mapperDeclClass.getKind() == J.ClassDeclaration.Kind.Type.Interface) {
                        mapperDeclStatement = transformMapperDeclInterfaceField(mapperDeclStatement)
                    }
                    copiedClassStatements.add(mapperDeclStatement)
                }
            }

            copiedClassStatements.sort(StatementDefinitionOrder())

            var clazz =
                mapperImplClass
                    .withBody(mapperImplClass.getBody().withStatements(copiedClassStatements))
                    .withName(mapperImplClass.getName().withSimpleName(mapperDeclClassName))
                    .withImplements(null)
                    .withLeadingAnnotations(
                        Stream
                            .concat<J.Annotation?>(
                                mapperDeclClass
                                    .getLeadingAnnotations()
                                    .stream()
                                    .filter { a: J.Annotation? -> Companion.excludeMapstructAnnotations(a!!) },
                                mapperImplClass
                                    .getLeadingAnnotations()
                                    .stream()
                                    .filter { a: J.Annotation? -> Companion.excludeGeneratedAnnotations(a!!) },
                            ).toList(),
                    ).withExtends(null)

            // The generated impl body was copied verbatim from the scan-time accumulator and never
            // visited by this processor. Now that it has been merged in, mutate it so the reference
            // rewrites apply to the copied statements too (e.g. the Mappers.getMapper factory calls
            // MapStruct emits for `uses` mappers, and any *Impl references inside method bodies).
            if (visit(clazz, ctx) is J.ClassDeclaration) {
                clazz = mutatedClazz
            }

            // Replace every simple-name type identifier with its FQN so the class compiles
            // without any imports.
            val qualified =
                object : JavaVisitor<ExecutionContext>() {
                    override fun visitIdentifier(
                        identifier: J.Identifier,
                        ctx: ExecutionContext,
                    ): J {
                        // Skip variable / field references.
                        if (identifier.getFieldType() != null) return identifier
                        if (identifier.getType() !is JavaType.FullyQualified) return identifier
                        val fqn: String = fqType.getFullyQualifiedName()
                        // Skip types in the default package (no dots — already unqualifiable).
                        if (!fqn.contains(".")) return identifier
                        // Skip the name segment of an already-qualified J.FieldAccess chain.
                        val nearestFa = getCursor().firstEnclosing<J.FieldAccess?>(J.FieldAccess::class.java)
                        if (nearestFa != null && nearestFa.getName() === identifier) return identifier
                        // Only replace when the identifier is currently using the simple name.
                        val simpleName = fqn.substring(fqn.lastIndexOf('.') + 1)
                        if (identifier.getSimpleName() != simpleName) return identifier
                        return buildFqnTypeTree(fqn, identifier.getPrefix())
                    }
                }.visit(clazz, ctx)
            if (qualified is J.ClassDeclaration) {
                clazz = qualified
            }

            return mapperImplFile
                .withClasses(mutableListOf<J.ClassDeclaration?>(clazz))
                .withId(visited.getId())
                .withSourcePath(visited.getSourcePath())
        } catch (e: Exception) {
            MapperProcessor.log.severe(
                (
                    "Error processing @Mapper class " +
                        visited.getClasses().get(0).getName() +
                        ": " +
                        e.message
                ),
            )
            throw RuntimeException(
                "Failed to migrate Mapstruct Mapper: " +
                    mapperDeclClass.getName().getSimpleName(),
                e,
            )
        }
    }

    /**
     * Replaces the MapStruct factory lookup `Mappers.getMapper(SomeMapper.class)` with a direct
     * constructor call `new SomeMapper()`. After inlining, the mapper is a concrete class, so
     * the factory call (which resolved the now-deleted generated implementation) becomes a plain
     * instantiation. The `org.mapstruct.factory.Mappers` import is dropped by [ ][.copyImports].
     */
    override fun visitMethodInvocation(
        method: J.MethodInvocation,
        ctx: ExecutionContext,
    ): J {
        val visited = super.visitMethodInvocation(method, ctx)
        if (visited !is J.MethodInvocation) {
            return visited
        }

        // Migrate `when(spy.x(a)).thenReturn(v)` into `doReturn(v).when(spy).x(a)`.
        // With the mapper inlined into a concrete class, `when(spy.x(a))` now invokes the real
        // method on the spy; `doReturn(...)` avoids that side effect and matches Mockito best
        // practice for spies.
        val rewrittenSpyStub = rewriteWhenOnSpyIfApplicable(visited, ctx)
        if (rewrittenSpyStub != null) {
            return rewrittenSpyStub
        }

        if (!isMappersGetMapper(visited) || visited.getArguments().size != 1) {
            return visited
        }

        // The single argument is a class literal: SomeMapper.class
        if (visited.getArguments().get(0) !is J.FieldAccess || classLiteral.getName().getSimpleName() != "class") {
            return visited
        }

        val mapperType: TypeTree?
        if (classLiteral.getTarget() is J.Identifier) {
            mapperType = identifier.withPrefix(Space.SINGLE_SPACE)
        } else if (classLiteral.getTarget() is J.FieldAccess) {
            mapperType = fieldAccess.withPrefix(Space.SINGLE_SPACE)
        } else {
            return visited
        }

        val mapperFqn = TypeUtils.asFullyQualified(mapperType!!.getType())
        if (mapperFqn == null) {
            return visited
        }

        // Synthesize the no-arg constructor type so the new J.NewClass carries a valid type.
        val constructorType: JavaType.Method =
            JavaType.Method(
                null,
                Flag.Public.getBitMask(),
                mapperFqn,
                "<constructor>",
                mapperFqn,
                mutableListOf<String?>(),
                mutableListOf<JavaType?>(),
                mutableListOf<JavaType?>(),
                mutableListOf<JavaType.FullyQualified?>(),
                null,
                null,
            )

        val noArguments: Expression = J.Empty(UUID.randomUUID(), Space.EMPTY, Markers.EMPTY)
        val arguments: JContainer<Expression> =
            JContainer.build<Expression?>(
                Space.EMPTY,
                mutableListOf<JRightPadded<Expression?>?>(JRightPadded.build<Expression?>(noArguments)),
                Markers.EMPTY,
            )

        // Mappers.getMapper(SomeMapper.class) -> new SomeMapper()
        return J.NewClass(
            UUID.randomUUID(),
            visited.getPrefix(),
            visited.getMarkers(),
            null,
            Space.EMPTY,
            mapperType,
            arguments,
            null,
            constructorType,
        )
    }

    /**
     * Replaces references of UserMapperImpl.class to UserMapper.class, both for the simple-name case
     * (`UserMapperImpl.class`) and the fully-qualified case (`com.foo.UserMapperImpl.class`).
     */
    override fun visitFieldAccess(
        fieldAccess_: J.FieldAccess,
        ctx: ExecutionContext,
    ): J {
        val visited = super.visitFieldAccess(fieldAccess_, ctx)
        if (visited !is J.FieldAccess) {
            return visited
        }

        val target = visited.getTarget()

        // Case A: simple-name target, e.g. `UserMapperImpl.class` or `UserMapperImpl.FIELD`.
        // Rewrite the identifier itself to point at the super type.
        if (target is J.Identifier) {
            val targetType = target.getType()
            if (targetType == null) {
                return visited
            }

            val targetFqn = targetType.toString()
            val superFqn = acc.getSuperFqnFromImplFqn(targetFqn)

            if (superFqn == null) {
                return visited
            }

            val superSimpleName = extractSimpleName(superFqn)
            val superType = JavaType.buildType(superFqn)
            val superTarget: Expression =
                J.Identifier(
                    UUID.randomUUID(),
                    target.getPrefix(),
                    target.getMarkers(),
                    mutableListOf<J.Annotation?>(),
                    superSimpleName,
                    superType,
                    target.getFieldType(),
                )

            return visited.withTarget(superTarget).withType(superType)
        }

        // Case B: fully-qualified target, e.g. `com.foo.UserMapperImpl.class`.
        // The target is itself a FieldAccess chain whose FQN (from the name chain, not the
        // possibly-stale type attribution) is the impl type. Rename the final segment.
        if (target is J.FieldAccess) {
            val targetFqn = extractFqnFromFieldAccess(target)
            if (targetFqn == null) {
                return visited
            }
            val superFqn = acc.getSuperFqnFromImplFqn(targetFqn)
            if (superFqn == null) {
                return visited
            }

            val superSimpleName = extractSimpleName(superFqn)
            val superType = JavaType.buildType(superFqn)
            val newFinalName = target.getName().withSimpleName(superSimpleName)
            val newTarget = target.withName(newFinalName).withType(superType)

            return visited.withTarget(newTarget)
        }

        return visited
    }

    /** Replaces import references of UserMapperImpl to UserMapper  */
    override fun visitImport(
        imp: J.Import,
        ctx: ExecutionContext,
    ): J {
        val visited = super.visitImport(imp, ctx)
        if (visited !is J.Import) {
            return visited
        }

        // Extract FQN from import qualid
        val importFqn = extractFqnFromFieldAccess(visited.getQualid())
        if (importFqn == null) {
            return visited
        }

        // Check if this is a mapper implementation that needs replacement
        val superFqn = acc.getSuperFqnFromImplFqn(importFqn)
        if (superFqn == null) {
            // Not a mapper impl - check if it's already a super type (to avoid replacing backwards)
            // If this FQN is a super type for some impl, don't touch it
            return visited
        }

        // Check if already replaced - the import FQN should match super FQN
        if (importFqn == superFqn) {
            return visited
        }

        // Check by simple name - if it matches and doesn't end with Impl, it's already replaced
        val currentSimpleName = getFinalIdentifierName(visited.getQualid())
        val expectedSimpleName = extractSimpleName(superFqn)
        if (currentSimpleName == expectedSimpleName && !currentSimpleName.endsWith("Impl")) {
            return visited
        }

        // Replace the import with the super type
        return replaceImportQualid(visited, superFqn)
    }

    /** Replaces instantiations of UserMapperImpl() to UserMapper()  */
    override fun visitNewClass(
        newClass: J.NewClass,
        ctx: ExecutionContext,
    ): J {
        val visited = super.visitNewClass(newClass, ctx)
        if (visited !is J.NewClass) {
            return visited
        }

        // Replace constructor type (new MyMapperImpl() -> new MyMapper())
        val clazz = visited.getClazz()
        if (clazz == null) {
            return visited
        }

        val replacedClazz = replaceTypeTreeIfNeeded(clazz)
        if (replacedClazz === clazz) {
            return visited
        }

        return visited.withClazz(replacedClazz)
    }

    /** Replaces variable declarations like `UserMapperImpl userMapper` to `UserMapper userMapper`  */
    override fun visitVariableDeclarations(
        multiVariable: J.VariableDeclarations,
        p: ExecutionContext,
    ): J {
        val visited = super.visitVariableDeclarations(multiVariable, p)
        if (visited !is J.VariableDeclarations) {
            return visited
        }

        // Replace type expression (for method parameters, field declarations, etc.)
        if (visited.getTypeExpression() == null) {
            return visited
        }

        val typeExpression: TypeTree = visited.getTypeExpression()!!
        val replacedTypeExpression = replaceTypeTreeIfNeeded(typeExpression)
        if (replacedTypeExpression === typeExpression) {
            return visited
        }

        return visited.withTypeExpression(replacedTypeExpression)
    }

    /**
     * Replaces instanceof checks like `userMapper instanceof UserMapperImpl` to `userMapper
     * instanceof UserMapper`
     */
    override fun visitInstanceOf(
        instanceOf_: J.InstanceOf,
        ctx: ExecutionContext,
    ): J {
        val visited = super.visitInstanceOf(instanceOf_, ctx)
        if (visited !is J.InstanceOf) {
            return visited
        }

        // Replace the type in instanceof checks
        val clazzExpr = visited.getClazz()
        if (clazzExpr !is J.ControlParentheses<*>) {
            return visited
        }

        val treeObj: Any = clazzExpr.getTree()
        if (treeObj !is TypeTree) {
            return visited
        }

        val replacedClazz = replaceTypeTreeIfNeeded(treeObj)
        if (replacedClazz === treeObj) {
            return visited
        }

        return visited.withClazz(clazzExpr.withTree(replacedClazz))
    }

    private fun copyImports(
        mapperImplementationFile: J.CompilationUnit,
        originalCompilationUnit: J.CompilationUnit,
    ): J.CompilationUnit = mapperImplementationFile.withImports(mutableListOf<J.Import?>())

    /**
     * Extracts FQN from a FieldAccess (used for imports). Prioritizes name-based extraction to avoid
     * stale type information after replacements.
     */
    private fun extractFqnFromFieldAccess(fieldAccess: J.FieldAccess): String? {
        // First try to extract from the name chain (more reliable after replacements)
        val parts: MutableList<String> = ArrayList<String>()
        var current = fieldAccess
        while (true) {
            parts.add(current.getName().getSimpleName())
            if (current.getTarget() is J.FieldAccess) {
                current = nested
            } else if (current.getTarget() is J.Identifier) {
                parts.add(identifier.getSimpleName())
                break
            } else {
                break
            }
        }
        Collections.reverse(parts)
        val nameBasedFqn = if (parts.isEmpty()) null else String.join(".", parts)

        // If we got a valid FQN from names, use it (more reliable after replacements)
        if (nameBasedFqn != null && !nameBasedFqn.isEmpty()) {
            return nameBasedFqn
        }

        // Fallback to type information if name extraction failed
        if (fieldAccess.getType() != null) {
            val type: JavaType = fieldAccess.getType()!!
            if (type is JavaType.FullyQualified) {
                return type.getFullyQualifiedName()
            }
            return type.toString()
        }

        return null
    }

    /** Replaces mentions of a type to it's super type (implements or extends).  */
    private fun replaceTypeTreeIfNeeded(typeTree: TypeTree): TypeTree {
        if (typeTree.getType() !is JavaType.FullyQualified) {
            return typeTree
        }

        val typeFqn: kotlin.String = type.getFullyQualifiedName()
        val superFqn = acc.getSuperFqnFromImplFqn(typeFqn)
        if (superFqn == null) {
            return typeTree
        }

        val superSimpleName = extractSimpleName(superFqn)

        val superType = JavaType.buildType(superFqn)
        return J.Identifier(
            UUID.randomUUID(),
            typeTree.getPrefix(),
            typeTree.getMarkers(),
            mutableListOf<J.Annotation?>(),
            superSimpleName,
            superType,
            null,
        )
    }

    /** Recursively replaces the final identifier in a FieldAccess chain.  */
    private fun replaceFinalIdentifierInChain(
        fieldAccess: J.FieldAccess,
        newIdentifier: J.Identifier,
    ): J.FieldAccess {
        if (fieldAccess.getTarget() is J.FieldAccess) {
            // Continue down the chain
            val newTarget = replaceFinalIdentifierInChain(nested, newIdentifier)
            return fieldAccess.withTarget(newTarget)
        }
        // This is the final FieldAccess, replace its name
        return fieldAccess.withName(newIdentifier)
    }

    /**
     * Replaces the qualid in an import statement with the super type. The root FieldAccess (returned
     * by getQualid()) has the class name as its name. We just need to replace that name.
     */
    private fun replaceImportQualid(
        import_: J.Import,
        superFqn: kotlin.String,
    ): J.Import {
        val superSimpleName = extractSimpleName(superFqn)
        val qualid = import_.getQualid()

        // The root FieldAccess's name is the class name we want to replace
        val rootName = qualid.getName()
        val newName = rootName.withSimpleName(superSimpleName)
        val newQualid = qualid.withName(newName)

        return import_.withQualid(newQualid)
    }

    /** Extracts the simple name (last part) from an FQN.  */
    private fun extractSimpleName(fqn: kotlin.String): kotlin.String {
        val lastDot = fqn.lastIndexOf('.')
        return if (lastDot >= 0) fqn.substring(lastDot + 1) else fqn
    }

    /** Gets the final identifier name from a FieldAccess chain.  */
    private fun getFinalIdentifierName(fieldAccess: J.FieldAccess): kotlin.String {
        var current = fieldAccess
        while (current.getTarget() is J.FieldAccess) {
            current = nested
        }
        return current.getName().getSimpleName()
    }

    /** Gets the simple name from a TypeTree.  */
    private fun getSimpleNameFromTypeTree(typeTree: TypeTree): kotlin.String {
        if (typeTree is J.Identifier) {
            return typeTree.getSimpleName()
        } else if (typeTree is J.FieldAccess) {
            return getFinalIdentifierName(typeTree)
        }
        return ""
    }

    /**
     * If `invocation` matches `when(spy.method(args)).thenReturn(value)` (or `thenThrow`), where `spy` is a locally declared `@Spy` field, rebuild the tree as
     * `doReturn(value).when(spy).method(args)` (or `doThrow(...)`) and add the necessary
     * Mockito static import. Returns `null` when the pattern doesn't match.
     */
    private fun rewriteWhenOnSpyIfApplicable(
        invocation: J.MethodInvocation,
        ctx: ExecutionContext,
    ): J.MethodInvocation? {
        val stubName = invocation.getSimpleName()
        if ("thenReturn" != stubName && "thenThrow" != stubName) {
            return null
        }
        if (invocation.getArguments().size != 1) {
            return null
        }

        val select = invocation.getSelect()
        if (select !is J.MethodInvocation) {
            return null
        }
        if ("when" != select.getSimpleName() || select.getArguments().size != 1) {
            return null
        }
        if (select.getArguments().get(0) !is J.MethodInvocation) {
            return null
        }
        val spyRef: Expression? = spyMethodCall.getSelect()
        if (spyRef !is J.Identifier) {
            return null
        }
        val spyNames: MutableSet<kotlin.String>? =
            getCursor().getNearestMessage<MutableSet<kotlin.String?>?>(
                SPY_FIELD_NAMES_KEY,
            )
        MapperProcessor.log.fine(
            (
                "[PurgeMapstruct] Checking when-spy: candidate=" +
                    spyRef.getSimpleName() +
                    " known-spies=" +
                    spyNames
            ),
        )
        if (spyNames == null || !spyNames.contains(spyRef.getSimpleName())) {
            return null
        }

        val doStubName = if ("thenReturn" == stubName) "doReturn" else "doThrow"
        val stubValue = invocation.getArguments().get(0)

        val mockitoType = JavaType.buildType("org.mockito.Mockito") as JavaType.FullyQualified
        val stubberType =
            JavaType.buildType("org.mockito.stubbing.Stubber") as JavaType.FullyQualified

        // Synthesize a matching Mockito.doReturn(Object) / doThrow(Throwable) method type so the
        // resulting LST has valid type attribution and validators are happy.
        val doStubMethodType: JavaType.Method =
            JavaType.Method(
                null,
                Flag.Public.getBitMask() or Flag.Static.getBitMask(),
                mockitoType,
                doStubName,
                stubberType,
                mutableListOf<kotlin.String?>("value"),
                mutableListOf<JavaType?>(
                    if (stubValue.getType() != null) stubValue.getType() else JavaType.buildType("java.lang.Object"),
                ),
                mutableListOf<JavaType?>(),
                mutableListOf<JavaType.FullyQualified?>(),
                null,
                null,
            )

        val doStubIdent =
            J.Identifier(
                UUID.randomUUID(),
                Space.EMPTY,
                Markers.EMPTY,
                mutableListOf<J.Annotation?>(),
                doStubName,
                doStubMethodType,
                null,
            )
        val doStubArgs: JContainer<Expression> =
            JContainer.build<Expression?>(
                Space.EMPTY,
                mutableListOf<JRightPadded<Expression?>?>(
                    JRightPadded.build<Expression?>(
                        stubValue.withPrefix<Expression?>(
                            Space.EMPTY,
                        ),
                    ),
                ),
                Markers.EMPTY,
            )
        val doStubCall =
            J.MethodInvocation(
                UUID.randomUUID(),
                invocation.getPrefix(),
                invocation.getMarkers(),
                null,
                null,
                doStubIdent,
                doStubArgs,
                doStubMethodType,
            )

        val newWhenCall =
            J.MethodInvocation(
                UUID.randomUUID(),
                Space.EMPTY,
                select.getMarkers(),
                JRightPadded.build<Expression?>(doStubCall as Expression),
                null,
                select.getName().withPrefix(Space.EMPTY),
                JContainer.build<Expression?>(
                    Space.EMPTY,
                    mutableListOf<JRightPadded<Expression?>?>(JRightPadded.build<Expression?>(spyRef.withPrefix(Space.EMPTY))),
                    Markers.EMPTY,
                ),
                select.getMethodType(),
            )

        val spyArgs: MutableList<Expression> = spyMethodCall.getArguments()
        val paddedFinalArgs: MutableList<JRightPadded<Expression>> = ArrayList<JRightPadded<Expression>>(spyArgs.size)
        for (i in spyArgs.indices) {
            val prefix = if (i == 0) Space.EMPTY else Space.SINGLE_SPACE
            paddedFinalArgs.add(JRightPadded.build<Expression?>(spyArgs.get(i).withPrefix<Expression?>(prefix)))
        }

        val finalCall =
            J.MethodInvocation(
                UUID.randomUUID(),
                Space.EMPTY,
                spyMethodCall.getMarkers(),
                JRightPadded.build<Expression?>(newWhenCall as Expression),
                null,
                spyMethodCall.getName().withPrefix(Space.EMPTY),
                JContainer.build<Expression?>(Space.EMPTY, paddedFinalArgs, Markers.EMPTY),
                spyMethodCall.getMethodType(),
            )

        // Queue up a static import for org.mockito.Mockito.doReturn / doThrow.
        doAfterVisit(AddImport<ExecutionContext?>("org.mockito.Mockito", doStubName, false))

        return finalCall
    }

    companion object {
        private const val MAPSTRUCT_GROUP = "org.mapstruct"

        private fun transformMapperDeclMethod(mapperDeclMethod: J.MethodDeclaration): J.MethodDeclaration? {
            // Don't copy declaration methods
            var mapperDeclMethod = mapperDeclMethod
            if (mapperDeclMethod.getBody() == null) {
                return null
            }

            mapperDeclMethod =
                mapperDeclMethod.withModifiers(
                    ListUtils.map<J.Modifier?>(
                        mapperDeclMethod.getModifiers(),
                        UnaryOperator { modifier: J.Modifier? ->
                            if (modifier!!.getType() == J.Modifier.Type.Default) {
                                return@map modifier.withType(J.Modifier.Type.Public)
                            }
                            modifier
                        },
                    ),
                )

            mapperDeclMethod =
                mapperDeclMethod.withLeadingAnnotations(
                    ListUtils.filter<J.Annotation?>(
                        mapperDeclMethod.getLeadingAnnotations(),
                        Predicate { a: J.Annotation? -> Companion.excludeMapstructAnnotations(a!!) },
                    ),
                )

            // Remove MapStruct annotations from method parameters
            val filteredParameters: MutableList<Statement> =
                ListUtils.map<Statement?>(
                    mapperDeclMethod.getParameters(),
                    UnaryOperator { param: Statement? ->
                        if (param is J.VariableDeclarations) {
                            return@map param.withLeadingAnnotations(
                                ListUtils.filter<J.Annotation?>(
                                    param.getLeadingAnnotations(),
                                    Predicate { a: J.Annotation? -> Companion.excludeMapstructAnnotations(a!!) },
                                ),
                            )
                        }
                        param
                    },
                )

            mapperDeclMethod = mapperDeclMethod.withParameters(filteredParameters)

            return mapperDeclMethod
        }

        private fun transformMapperDeclInterfaceField(mapperDeclField: J.VariableDeclarations): J.VariableDeclarations {
            var mapperDeclField = mapperDeclField
            val modifiers = ArrayList<J.Modifier>()

            val accessModifiers =
                Set.of<J.Modifier.Type?>(J.Modifier.Type.Public, J.Modifier.Type.Protected, J.Modifier.Type.Private)

            val modifiersSetManually =
                Set.of<J.Modifier.Type?>(
                    J.Modifier.Type.Public,
                    J.Modifier.Type.Protected,
                    J.Modifier.Type.Private,
                    J.Modifier.Type.Static,
                    J.Modifier.Type.Final,
                )

            val accessModifierInPlace =
                mapperDeclField
                    .getModifiers()
                    .stream()
                    .filter { modifier: J.Modifier? -> accessModifiers.contains(modifier!!.getType()) }
                    .findFirst()

            if (accessModifierInPlace.isPresent()) {
                modifiers.add(accessModifierInPlace.get())
            } else {
                modifiers.add(
                    J.Modifier(
                        UUID.randomUUID(),
                        Space.EMPTY,
                        Markers.EMPTY,
                        null,
                        J.Modifier.Type.Public,
                        mutableListOf<J.Annotation?>(),
                    ),
                )
            }

            modifiers.add(
                J.Modifier(
                    UUID.randomUUID(),
                    Space.SINGLE_SPACE,
                    Markers.EMPTY,
                    null,
                    J.Modifier.Type.Static,
                    mutableListOf<J.Annotation?>(),
                ),
            )

            modifiers.add(
                J.Modifier(
                    UUID.randomUUID(),
                    Space.SINGLE_SPACE,
                    Markers.EMPTY,
                    null,
                    J.Modifier.Type.Final,
                    mutableListOf<J.Annotation?>(),
                ),
            )

            for (modifier in mapperDeclField.getModifiers()) {
                if (!modifiersSetManually.contains(modifier.getType())) {
                    modifiers.add(modifier.withPrefix(Space.SINGLE_SPACE))
                }
            }

            // Ensure the type expression has proper spacing after modifiers
            mapperDeclField = mapperDeclField.withModifiers(modifiers)
            if (mapperDeclField.getTypeExpression() != null) {
                mapperDeclField =
                    mapperDeclField.withTypeExpression(
                        mapperDeclField.getTypeExpression()!!.withPrefix<TypeTree?>(Space.SINGLE_SPACE),
                    )
            }

            return mapperDeclField
        }

        private fun transformMapperImplMethod(
            implMethod: J.MethodDeclaration,
            mapperImplClassName: kotlin.String,
            mapperDeclClassName: kotlin.String,
        ): J.MethodDeclaration {
            // Rename the constructor
            var implMethod = implMethod
            val isConstructor = implMethod.getName().getSimpleName() == mapperImplClassName
            if (isConstructor) {
                implMethod = implMethod.withName(implMethod.getName().withSimpleName(mapperDeclClassName))
            }

            // Filter out annotations that look like Override or Named
            // When removing @Override, we need to preserve the spacing before it
            val originalAnnotations = implMethod.getLeadingAnnotations()
            var prefixToPreserve: Space? = null

            // Find if we're removing an @Override annotation and capture its prefix
            for (annotation in originalAnnotations) {
                if (annotation.getSimpleName() == "Override" ||
                    TypeUtils.isOfClassType(annotation.getType(), "java.lang.Override")
                ) {
                    prefixToPreserve = annotation.getPrefix()
                    break
                }
            }

            val filteredAnnotations: MutableList<J.Annotation> =
                ListUtils.map<J.Annotation?>(
                    originalAnnotations,
                    UnaryOperator { methodAnnotation: J.Annotation ->
                        if (methodAnnotation.getSimpleName() == "Override" ||
                            TypeUtils.isOfClassType(methodAnnotation.getType(), "java.lang.Override")
                        ) {
                            return@map null
                        }
                        methodAnnotation
                    },
                )

            implMethod = implMethod.withLeadingAnnotations(filteredAnnotations)

            // If we removed annotations and captured the prefix, apply it to the method
            if (prefixToPreserve != null && filteredAnnotations.isEmpty()) {
                implMethod = implMethod.withPrefix(prefixToPreserve)
            }

            return implMethod
        }

        private fun excludeGeneratedAnnotations(a: J.Annotation): Boolean =
            !(
                a.getSimpleName() == "Generated" ||
                    TypeUtils.isOfClassType(a.getType(), "javax.annotation.processing.Generated") ||
                    TypeUtils.isOfClassType(a.getType(), "jakarta.annotation.Generated")
            )

        /**
         * Simple names of MapStruct annotations, used as a fallback when an annotation's type cannot be
         * resolved to its fully qualified name (e.g. partial type attribution). Mirrors the public
         * annotations in the `org.mapstruct` package.
         */
        private val MAPSTRUCT_ANNOTATION_SIMPLE_NAMES: MutableSet<kotlin.String> =
            mutableSetOf<kotlin.String?>(
                "AfterMapping",
                "BeanMapping",
                "BeforeMapping",
                "Condition",
                "Context",
                "DecoratedWith",
                "EnumMapping",
                "InheritConfiguration",
                "InheritInverseConfiguration",
                "IterableMapping",
                "MapMapping",
                "Mapper",
                "MapperConfig",
                "Mapping",
                "MappingConstants",
                "Mappings",
                "MappingTarget",
                "Named",
                "ObjectFactory",
                "Qualifier",
                "SubclassMapping",
                "SubclassMappings",
                "TargetType",
                "ValueMapping",
                "ValueMappings",
            )

        private fun excludeMapstructAnnotations(a: J.Annotation): Boolean {
            val type = a.getType()

            // When the type resolves, rely on the fully qualified name.
            if (type != null && type !is JavaType.Unknown) {
                return !type.toString().startsWith(MAPSTRUCT_GROUP)
            }

            // Otherwise fall back to the annotation's simple name (e.g. @AfterMapping, @MappingTarget),
            // so MapStruct annotations are still removed even without full type attribution.
            return !MAPSTRUCT_ANNOTATION_SIMPLE_NAMES.contains(a.getSimpleName())
        }

        /**
         * Cursor message key: `Set<String>` of local field names in the current compilation unit
         * that are annotated with Mockito's `@Spy`. Populated at the top of [ ][.visitCompilationUnit] so nested visitors (notably [ ][.visitMethodInvocation]) can rewrite `when(spy.x(a)).thenReturn(v)` into `doReturn(v).when(spy).x(a)`.
         */
        private const val SPY_FIELD_NAMES_KEY = "purgeMapstruct.spyFieldNames"

        private fun isMappersGetMapper(invocation: J.MethodInvocation): Boolean {
            if ("getMapper" != invocation.getSimpleName()) {
                return false
            }

            val methodType = invocation.getMethodType()
            if (methodType != null && methodType.getDeclaringType() != null) {
                return (
                    "org.mapstruct.factory.Mappers"
                        == methodType.getDeclaringType().getFullyQualifiedName()
                )
            }

            // Fall back to the select's simple name when type attribution is missing.
            val select = invocation.getSelect()
            if (select is J.Identifier) {
                return "Mappers" == select.getSimpleName()
            }
            if (select is J.FieldAccess) {
                return "Mappers" == select.getName().getSimpleName()
            }
            return false
        }

        /**
         * Builds a fully-qualified type tree (a chain of [J.FieldAccess] nodes) from a
         * dot-separated FQN string — the AST equivalent of writing `com.example.Foo` as a type
         * reference in source code without an import.
         */
        private fun buildFqnTypeTree(
            fqn: kotlin.String,
            prefix: Space,
        ): TypeTree {
            val parts = fqn.split("\\.".toRegex()).dropLastWhile { it.isEmpty() }.toTypedArray()
            var current: Expression =
                J.Identifier(
                    UUID.randomUUID(),
                    Space.EMPTY,
                    Markers.EMPTY,
                    mutableListOf<J.Annotation?>(),
                    parts[0],
                    null,
                    null,
                )
            for (i in 1..<parts.size) {
                val isLast = i == parts.size - 1
                val type = if (isLast) JavaType.buildType(fqn) else null
                val namePart =
                    J.Identifier(
                        UUID.randomUUID(),
                        Space.EMPTY,
                        Markers.EMPTY,
                        mutableListOf<J.Annotation?>(),
                        parts[i],
                        type,
                        null,
                    )
                current =
                    J.FieldAccess(
                        UUID.randomUUID(),
                        Space.EMPTY,
                        Markers.EMPTY,
                        current,
                        JLeftPadded.build<J.Identifier?>(namePart),
                        type,
                    )
            }
            if (parts.size == 1) {
                return (current as J.Identifier).withPrefix(prefix)
            }
            return (current as J.FieldAccess).withPrefix(prefix)
        }

        /**
         * Collects the simple names of top-level fields (declared on the file's outer classes) that carry
         * the Mockito `@Spy` annotation. Used to scope the spy-stubbing rewrite so it only fires on
         * locally-declared spies.
         */
        private fun collectSpyFieldNames(cu: J.CompilationUnit): MutableSet<kotlin.String> {
            val names: MutableSet<kotlin.String> = HashSet<kotlin.String>()
            for (clazz in cu.getClasses()) {
                for (stmt in clazz.getBody().getStatements()) {
                    if (stmt !is J.VariableDeclarations) {
                        continue
                    }
                    val isSpy =
                        stmt
                            .getLeadingAnnotations()
                            .stream()
                            .anyMatch { a: J.Annotation? ->
                                "Spy" == a!!.getSimpleName() ||
                                    TypeUtils.isOfClassType(a.getType(), "org.mockito.Spy")
                            }
                    if (!isSpy) {
                        continue
                    }
                    for (nv in stmt.getVariables()) {
                        names.add(nv.getSimpleName())
                    }
                }
            }
            return names
        }
    }
}
